ignore streams less than 30 seconds, segment streams over 12 hours

diff --git a/src/00-streamlink b/src/00-streamlink
--- a/src/00-streamlink
+++ b/src/00-streamlink
@@ -134,16 +134,28 @@ then
   done
 
   shopt -s globstar nullglob
-  for INPUT in **/*.ts
+  for INPUT in ./**/*.ts
   do
-    OUTPUT="${INPUT%.ts}.mp4"
+    if [ $(echo "$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$INPUT") >= 30" | bc) -eq 1 ]
+    then
+      CHKSUM="./.$(sha256sum <<<"$INPUT" | cut -d' ' -f1)"
+      PREFIX="${INPUT%.ts}"
 
-    echo "Remuxing '$INPUT' from MPEG-TS to MPEG-4 ..." >&2
-    ffmpeg -i "$INPUT" -c copy "$OUTPUT" || echo "Error: '$INPUT' remux exited with non-zero code: $?" >&2
+      echo "Remuxing '$INPUT' from MPEG-TS to MPEG-4 ..." >&2
+      ffmpeg -i "$INPUT" -t 172800 -c copy -f segment -reset_timestamps 1 -segment_time 43200 "$CHKSUM".part%d.mp4 || echo "Error: '$INPUT' remux exited with non-zero code: $?" >&2
 
+      FILES=("$CHKSUM".part[0-3].mp4)
+      if [ "${#FILES[@]}" -eq 1 ]
+      then
+        SRC="${FILES[@]}"
+        DST="${PREFIX}.mp4"
+
+        echo "Renaming '$SRC' to '$DST' ..." >&2
+        mv "$SRC" "$DST"
+      fi
+    fi
+
+    echo "Removing '$INPUT' ..." >&2
     rm -f "$INPUT"
   done
-
-  echo 'Pruning short MPEG-4 files ...' >&2
-  find -type f -name '*.mp4' -size -128M -print -delete
 fi
