update 00-streamlink

diff --git a/src/00-streamlink b/src/00-streamlink
--- a/src/00-streamlink
+++ b/src/00-streamlink
@@ -183,7 +183,7 @@ then
         then
           INT=$(dirname "$DST")/.$(basename "$DST").temp
 
-          pv --interval=30 --rate-limit=10M < "$TMP" > "$INT" && mv "$INT" "$DST" || { echo "Error: '$INPUT' copy exited with non-zero code: $?" >&2; truncate -s 0 "$TMP" "$INT" "$DST" || true; rm -f "$TMP" "$INT" "$DST"; }
+          pv --force --interval=30 --rate-limit=10M < "$TMP" > "$INT" && mv "$INT" "$DST" || { echo "Error: '$INPUT' copy exited with non-zero code: $?" >&2; truncate -s 0 "$TMP" "$INT" "$DST" || true; rm -f "$TMP" "$INT" "$DST"; }
 
           if [ -f "$TMP" ]
           then
